# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - "**.yml"

name: $(Date:yyyyMMdd)$(Rev:.r)_
variables:
- group: SharePoint Deployment

jobs:
  - job: Job_1
    displayName: SPFx Package Building Agent
    pool:
      vmImage: ubuntu-20.04
    steps:
      - checkout: self
      - task: NodeTool@0
        displayName: Install Node 14.15.0
        inputs:
          versionSpec: '14.15.0'
      - task: Npm@1
        displayName: Install npm
        inputs:
          command: 'install'
          workingDir: '$(ProjectFolder)'
          verbose: true
      - task: gulp@0
        displayName: SPFx - Bundle Solution
        inputs:
          gulpFile: '$(ProjectFolder)/gulpfile.js'
          targets: 'bundle'
          arguments: '--ship'
          cwd: '$(ProjectFolder)'
      - task: gulp@0
        displayName: SPFx - Ship the solution
        inputs:
          gulpFile: '$(ProjectFolder)/gulpfile.js'
          targets: 'package-solution'
          arguments: '--ship'
          cwd: $(ProjectFolder)

