# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - "**.yml"

name: $(Date:yyyyMMdd)$(Rev:.r)_
variables:
- group: SharePoint Deployment

jobs:
  - job: Job_1
    displayName: SPFx Package Building Agent
    pool:
      vmImage: ubuntu-20.04
    steps:
      - checkout: self
      - task: NodeTool@0
        displayName: 'Use Node 16.x'
        inputs:
          versionSpec: '16.x'
      - task: Npm@1
        displayName: Install npm
        inputs:
          workingDir: '.'
      - task: gulp@0
        displayName: SPFx - Bundle Solution
        inputs:
          gulpFile: ./gulpfile.js
          targets: 'bundle'
          arguments: '--ship'
      - task: gulp@0
        displayName: SPFx - Ship the solution
        inputs:
          gulpFile: ./gulpfile.js
          targets: 'package-solution'
          arguments: '--ship'
      - task: CopyFiles@2
        displayName: Copy sppkg-file to artifact staging directory 
        inputs:
          SourceFolder: '.'
          Contents: '$(SolutionPackageLocation)/$(PackageName)'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'
          flattenFolders: true
      - task: PublishBuildArtifacts@1
        displayName: 'Publish staged artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'


